"""Equivalencias explícitas de títulos curriculares; no mezcla técnicos por parecido."""
import re

from core.excel_parser import normalize_text


def text_key(value):
    return " ".join(re.sub(r"[^\w\s]", " ", normalize_text(value)).split())


# Abreviaturas y variantes verificadas en las mallas. Se conserva siempre el
# título original en el resultado importado, independientemente del catálogo.
FAMILIES = [
    ("FÍSICA", (r"FISICA", r"APLICACION DE CONOCIMIENTOS DE (?:LA FISICA|LAS CIENCIAS NATURALES) DE ACUERDO CON SITUACI.* DEL CONTEXTO PRODUCTIVO Y SOCIAL(?: FISICA)?")),
    ("MATEMÁTICAS", (r"MATEMATICAS", r"RAZONAR CUANTITATIVAMENTE FRENTE A SITUACIONES SUSCEPTIBLES DE SER ABORDAD.* MANERA MATEMATICA EN CONTEXTOS LABORALES SOCIALES(?: Y(?: PERSONALES)?)?")),
    ("TIC", (r"TIC", r"TECNOLOGIAS DE LA INFORMACION Y LA COMUNICACION", r"APLICACION DE TECNOLOGIAS DE LA INFORMACION Y LA COMUNICACION TIC DE ACUERDO CON LAS NECESIDADES DEL ENTORNO", r"UTILIZAR HERRAMIENTAS INFORMATICAS DE ACUERDO CON NECESIDADES DE MANEJO DE (?:INFORMACION|RMACION)")),
    ("COMUNICACIÓN", (r"COMUNICACION", r"DESARROLLAR PROCESOS DE COMUNICACION (?:EFICACES Y EFECTIVOS|ORAL Y ESCRITOS EN FORMA EFICAZ Y EFECTIVA) TENIENDO EN CUE(?:NTA)? SITUACIONES DE ORDEN SOCIAL PERSONAL Y PRODUCTIVO")),
    ("INVESTIGACIÓN", (r"INVESTIGACION", r"DESARROLLO DE PROCESOS DE INVESTIGACION EFECTIVOS TENIENDO EN CUENTA SITUACIONES DE ORDEN SOCIAL Y PRODUCTIVO")),
    ("PROTECCIÓN AMBIENTAL, SEGURIDAD Y SALUD EN EL TRABAJO", (r"PROTECCION AMBIENTAL SEGURIDAD Y SALUD EN EL TRABAJO", r"PROTECCION PARA LA SALUD Y EL MEDIO AMBIENTE", r"APLICAR PRACTICAS DE PROTECCION AMBIENTAL SEGURIDAD Y SALUD EN (?:EL )?TRABAJO DE (?:ACUERDO|ERDO) CON LAS POLITICAS ORGANIZACIONALES Y LA NORMATIVIDAD VIGENTE")),
    ("ACTIVIDAD FÍSICA Y HÁBITOS DE VIDA SALUDABLE", (r"ACTIVIDAD FISICA Y HABITOS DE VIDA SALUDABLE", r"GENERACION DE HABITOS SALUDABLES DE VIDA MEDIANTE LA APLICACION DE PROGRAMAS DE ACTIVIDAD FISICA EN LOS CONTEXTOS PRODUCTIVOS Y SOCIALES", r"IMPLEMENTAR HABITOS SALUDABLES MEDIANTE LA ACTIVIDAD FISICA DE CONFORMIDAD CON LAS EXIGENCIAS DEL PERFIL IDONEO DE EGRESO")),
    ("ÉTICA PARA LA CONSTRUCCIÓN DE UNA CULTURA DE PAZ", (r"ETICA PARA LA CONSTRUCCION DE UNA CULTURA DE PAZ", r"ETICA Y PAZ", r"INTERACTUAR EN EL CONTEXTO PRODUCTIVO Y SOCIAL DE ACUERDO CON PRINCIPIOS ETICOS PARA LA CONSTRUCCION DE UNA CULTURA DE PAZ")),
    ("DERECHOS FUNDAMENTALES DEL TRABAJO", (r"DERECHOS FUNDAMENTALES DEL TRABAJO", r"EJERCICIO DE LOS DERECHOS FUNDAMENTALES DEL TRABAJO", r"EJERCER DERECHOS FUNDAMENTALES DEL TRABAJO EN EL MARCO DE LA CONSTITUCION POLITICA Y LOS CONVENIOS INTERNACIONALES")),
    ("CULTURA EMPRENDEDORA Y EMPRESARIAL", (r"CULTURA EMPRENDEDORA Y EMPRESARIAL", r"EMPLEAR ELEMENTOS DE CULTURA EMPRENDEDORA Y EMPRESARIAL DE ACUERDO CON LOS CONTEXTOS PRODUCTIVOS SOCIAL Y PERSONAL", r"GESTIONAR PROCESOS (?:PRODUCTIVOS|PROPIOS) DE LA CULTURA EMPRENDEDORA Y EMPRESARIAL DE ACUERDO CON EL PERFIL PERSONAL Y LOS REQUERIMIENTOS DE LOS CONTEXTOS(?: PRODUCTIVO Y SOCIAL)?", r"FOMENTAR CULTURA EMPRENDEDORA SEGUN HABILIDADES Y COMPETENCIAS PERSONALES")),
    ("INGLES", (r"INGLES", r"BILINGUISMO", r"INTERACTUAR EN LENGUA INGLESA DE FORMA ORAL Y ESCRITA DENTRO DE CONTEXTOS SOCIALES Y LABORALES SEGUN LOS CRITERIOS ESTABLECIDOS POR EL MARCO COMUN EUROPEO DE REFERENCIA PARA LAS LENGUAS")),
]


def competency_identity(value):
    key = text_key(value)
    for display, variants in FAMILIES:
        if any(re.fullmatch(pattern, key) for pattern in variants):
            return text_key(display), display
    return key, " ".join(str(value).split()).strip(" .")


def automatic_classification(name, source_types):
    """Una clasificación explícita del Excel prevalece; sin ella se usa el título."""
    labels = {normalize_text(value) for value in source_types if str(value).strip()}
    if any("BILING" in label for label in labels):
        return True, "Bilingüismo"
    if any("INTEGRAL" in label or "TRANSVERSAL" in label for label in labels):
        return True, "Bilingüismo" if re.search(r"\b(INGLES|INGLESA|ENGLISH|BILINGUISMO)\b", text_key(name)) else "Integralidad"
    if labels & {"TECNICA", "TECNICO"}:
        return False, "Integralidad"
    key, _ = competency_identity(name)
    english = bool(re.search(r"\b(INGLES|INGLESA|ENGLISH|BILINGUISMO)\b", key))
    return english or key in {text_key(display) for display, _ in FAMILIES}, "Bilingüismo" if english else "Integralidad"
